# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidly_app', '0002_auto_20161122_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidly_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
