# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidly_app', '0004_auto_20161128_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default='Misc', on_delete=django.db.models.deletion.PROTECT, to='bidly_app.Category'),
            preserve_default=False,
        ),
    ]
